name: postmanTask
on: [push]
jobs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '16',
          node-version: '18'
      - run: npm install -g node
      - run: npm install -g newman
      - run: npm run newman Books.postman_collection -e test.postman_environment
