name: postmanTask
run-name: ${{ github.actor }} is postmanTask
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '16',
          node-version: '18'
      - run: npm install -g b
      - run: bats -v

     steps:  
    - run: npm install -g newman
- uses: actions/checkout@master
- uses: matt-ball/newman-action@master
   - run: npm run newman Books.postman_collection -e test.postman_environment
